AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRailsVersion: 3.4
plugins:
  - standard-custom
  - standard-performance
  - standard-rails
  - rubocop-minitest
inherit_gem:
  standard: config/base.yml
  standard-custom: config/base.yml
  standard-performance: config/base.yml
